// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHVwYUOl5XobBY9ozC48aTsN2Bw7o0o6I',
    appId: '1:139963798179:web:1059d5bcff7eaefeaba516',
    messagingSenderId: '139963798179',
    projectId: 'continuetodolistapp-b0fb1',
    authDomain: 'continuetodolistapp-b0fb1.firebaseapp.com',
    storageBucket: 'continuetodolistapp-b0fb1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLli-9kdp-we9ko8xmngm9IXURnjtGi3U',
    appId: '1:139963798179:android:d4a06a810e3ab227aba516',
    messagingSenderId: '139963798179',
    projectId: 'continuetodolistapp-b0fb1',
    storageBucket: 'continuetodolistapp-b0fb1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHVwYUOl5XobBY9ozC48aTsN2Bw7o0o6I',
    appId: '1:139963798179:web:9bbd1192a7f71b84aba516',
    messagingSenderId: '139963798179',
    projectId: 'continuetodolistapp-b0fb1',
    authDomain: 'continuetodolistapp-b0fb1.firebaseapp.com',
    storageBucket: 'continuetodolistapp-b0fb1.firebasestorage.app',
  );
}
